"""loans model upgraded

Revision ID: 3f73e53da4a3
Revises: 3382562d10b9
Create Date: 2025-12-02 18:46:42.299346

"""
from typing import Sequence, Union

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3f73e53da4a3'
down_revision: Union[str, Sequence[str], None] = '3382562d10b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    loan_status_enum = sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='loanstatus')
    loan_status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('due_dt', sa.Date(), nullable=False))
    op.add_column('loans', sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('loans', sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='loanstatus'), nullable=False, server_default='ACTIVE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'status')
    op.drop_column('loans', 'fine_amount')
    op.drop_column('loans', 'due_dt')
    # ### end Alembic commands ###
    loan_status_enum = sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='loanstatus')
    loan_status_enum.drop(op.get_bind())
